package ru.ezhov.rocket.action.icon

enum class AppIcon(val iconName: String) {
    ROCKET_APP("/rocket_16x16.png"),
    WRENCH("wrench-2x"),
    RELOAD("reload-2x"),
    PENCIL("pencil-2x"),
    STAR("star-2x"),
    INFO("info-2x"),
    X("x-2x"),
    MOVE("move-2x"),
    BOOKMARK("bookmark-2x"),
    PROJECT("project-2x"),
    IMAGE("image-2x"),
    FILE("file-2x"),
    LINK_INTACT("link-intact-2x"),
    CLIPBOARD("clipboard-2x"),
    FIRE("fire-2x"),
    WARNING("warning-2x"),
    BAN("ban-2x"),
    CLEAR("circle-x-2x"),
    TEXT("text-2x"),
    FLASH("flash-2x"),
    BOLT("bolt-2x"),
    ARROW_TOP("arrow-top-2x"),
    ARROW_BOTTOM("arrow-bottom-2x"),
    COPY_WRITING("copywriting-2x"),
    BROWSER("browser-2x"),
    LOADER("/load_16x16.gif"),
}