package ru.ezhov.rocket.action.application.resources

import javax.swing.ImageIcon

object Icons {
    object Standard {
        val ACCOUNT_LOGIN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-login.png"))
        val ACCOUNT_LOGOUT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-logout.png"))
        val ACTION_REDO_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-redo.png"))
        val ACTION_UNDO_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-undo.png"))
        val ALIGN_CENTER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-center.png"))
        val ALIGN_LEFT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-left.png"))
        val ALIGN_RIGHT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-right.png"))
        val APERTURE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/aperture.png"))
        val ARROW_BOTTOM_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-bottom.png"))
        val ARROW_CIRCLE_BOTTOM_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-bottom.png"))
        val ARROW_CIRCLE_LEFT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-left.png"))
        val ARROW_CIRCLE_RIGHT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-right.png"))
        val ARROW_CIRCLE_TOP_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-top.png"))
        val ARROW_LEFT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-left.png"))
        val ARROW_RIGHT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-right.png"))
        val ARROW_THICK_BOTTOM_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-bottom.png"))
        val ARROW_THICK_LEFT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-left.png"))
        val ARROW_THICK_RIGHT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-right.png"))
        val ARROW_THICK_TOP_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-top.png"))
        val ARROW_TOP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-top.png"))
        val AUDIO_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio.png"))
        val AUDIO_SPECTRUM_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio-spectrum.png"))
        val BADGE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/badge.png"))
        val BAN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ban.png"))
        val BAR_CHART_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bar-chart.png"))
        val BASKET_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/basket.png"))
        val BATTERY_EMPTY_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-empty.png"))
        val BATTERY_FULL_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-full.png"))
        val BEAKER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/beaker.png"))
        val BELL_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bell.png"))
        val BLUETOOTH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bluetooth.png"))
        val BOLD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bold.png"))
        val BOLT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bolt.png"))
        val BOOK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/book.png"))
        val BOOKMARK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bookmark.png"))
        val BOX_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/box.png"))
        val BRIEFCASE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/briefcase.png"))
        val BRITISH_POUND_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/british-pound.png"))
        val BROWSER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/browser.png"))
        val BRUSH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/brush.png"))
        val BUG_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bug.png"))
        val BULLHORN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bullhorn.png"))
        val CALCULATOR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calculator.png"))
        val CALENDAR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calendar.png"))
        val CAMERA_SLR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/camera-slr.png"))
        val CARET_BOTTOM_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-bottom.png"))
        val CARET_LEFT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-left.png"))
        val CARET_RIGHT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-right.png"))
        val CARET_TOP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-top.png"))
        val CART_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cart.png"))
        val CHAT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chat.png"))
        val CHECK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/check.png"))
        val CHEVRON_BOTTOM_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-bottom.png"))
        val CHEVRON_LEFT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-left.png"))
        val CHEVRON_RIGHT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-right.png"))
        val CHEVRON_TOP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-top.png"))
        val CIRCLE_CHECK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-check.png"))
        val CIRCLE_X_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-x.png"))
        val CLIPBOARD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clipboard.png"))
        val CLOCK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clock.png"))
        val CLOUD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud.png"))
        val CLOUD_DOWNLOAD_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-download.png"))
        val CLOUD_UPLOAD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-upload.png"))
        val CLOUDY_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloudy.png"))
        val CODE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/code.png"))
        val COG_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cog.png"))
        val COLLAPSE_DOWN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-down.png"))
        val COLLAPSE_LEFT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-left.png"))
        val COLLAPSE_RIGHT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-right.png"))
        val COLLAPSE_UP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-up.png"))
        val COMMAND_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/command.png"))
        val COMMENT_SQUARE_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/comment-square.png"))
        val COMPASS_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/compass.png"))
        val CONTRAST_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/contrast.png"))
        val COPYWRITING_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/copywriting.png"))
        val CREDIT_CARD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/credit-card.png"))
        val CROP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/crop.png"))
        val DASHBOARD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dashboard.png"))
        val DATA_TRANSFER_DOWNLOAD_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-download.png"))
        val DATA_TRANSFER_UPLOAD_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-upload.png"))
        val DELETE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/delete.png"))
        val DIAL_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dial.png"))
        val DOCUMENT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/document.png"))
        val DOLLAR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dollar.png"))
        val DOUBLE_QUOTE_SANS_LEFT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-left.png"))
        val DOUBLE_QUOTE_SANS_RIGHT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-right.png"))
        val DOUBLE_QUOTE_SERIF_LEFT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-left.png"))
        val DOUBLE_QUOTE_SERIF_RIGHT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-right.png"))
        val DROPLET_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/droplet.png"))
        val EJECT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eject.png"))
        val ELEVATOR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/elevator.png"))
        val ELLIPSES_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ellipses.png"))
        val ENVELOPE_CLOSED_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-closed.png"))
        val ENVELOPE_OPEN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-open.png"))
        val EURO_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/euro.png"))
        val EXCERPT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/excerpt.png"))
        val EXPAND_DOWN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-down.png"))
        val EXPAND_LEFT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-left.png"))
        val EXPAND_RIGHT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-right.png"))
        val EXPAND_UP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-up.png"))
        val EXTERNAL_LINK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/external-link.png"))
        val EYE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eye.png"))
        val EYEDROPPER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eyedropper.png"))
        val FILE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/file.png"))
        val FIRE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fire.png"))
        val FLAG_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flag.png"))
        val FLASH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flash.png"))
        val FOLDER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/folder.png"))
        val FORK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fork.png"))
        val FULLSCREEN_ENTER_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-enter.png"))
        val FULLSCREEN_EXIT_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-exit.png"))
        val GLOBE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/globe.png"))
        val GRAPH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/graph.png"))
        val GRID_FOUR_UP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-four-up.png"))
        val GRID_THREE_UP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-three-up.png"))
        val GRID_TWO_UP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-two-up.png"))
        val HARD_DRIVE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/hard-drive.png"))
        val HEADER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/header.png"))
        val HEADPHONES_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/headphones.png"))
        val HEART_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/heart.png"))
        val HOME_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/home.png"))
        val IMAGE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/image.png"))
        val INBOX_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/inbox.png"))
        val INFINITY_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/infinity.png"))
        val INFO_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/info.png"))
        val ITALIC_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/italic.png"))
        val JUSTIFY_CENTER_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-center.png"))
        val JUSTIFY_LEFT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-left.png"))
        val JUSTIFY_RIGHT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-right.png"))
        val KEY_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/key.png"))
        val LAPTOP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/laptop.png"))
        val LAYERS_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/layers.png"))
        val LIGHTBULB_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lightbulb.png"))
        val LINK_BROKEN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-broken.png"))
        val LINK_INTACT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-intact.png"))
        val LIST_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list.png"))
        val LIST_RICH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list-rich.png"))
        val LOCATION_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/location.png"))
        val LOCK_LOCKED_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-locked.png"))
        val LOCK_UNLOCKED_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-unlocked.png"))
        val LOOP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop.png"))
        val LOOP_CIRCULAR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-circular.png"))
        val LOOP_SQUARE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-square.png"))
        val MAGNIFYING_GLASS_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/magnifying-glass.png"))
        val MAP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map.png"))
        val MAP_MARKER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map-marker.png"))
        val MEDIA_PAUSE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-pause.png"))
        val MEDIA_PLAY_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-play.png"))
        val MEDIA_RECORD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-record.png"))
        val MEDIA_SKIP_BACKWARD_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-backward.png"))
        val MEDIA_SKIP_FORWARD_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-forward.png"))
        val MEDIA_STEP_BACKWARD_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-backward.png"))
        val MEDIA_STEP_FORWARD_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-forward.png"))
        val MEDIA_STOP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-stop.png"))
        val MEDICAL_CROSS_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/medical-cross.png"))
        val MENU_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/menu.png"))
        val MICROPHONE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/microphone.png"))
        val MINUS_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/minus.png"))
        val MONITOR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/monitor.png"))
        val MOON_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/moon.png"))
        val MOVE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/move.png"))
        val MUSICAL_NOTE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/musical-note.png"))
        val PAPERCLIP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/paperclip.png"))
        val PENCIL_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pencil.png"))
        val PEOPLE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/people.png"))
        val PERSON_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/person.png"))
        val PHONE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/phone.png"))
        val PIE_CHART_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pie-chart.png"))
        val PIN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pin.png"))
        val PLAY_CIRCLE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/play-circle.png"))
        val PLUS_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/plus.png"))
        val POWER_STANDBY_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/power-standby.png"))
        val PRINT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/print.png"))
        val PROJECT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/project.png"))
        val PULSE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pulse.png"))
        val PUZZLE_PIECE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/puzzle-piece.png"))
        val QUESTION_MARK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/question-mark.png"))
        val RAIN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rain.png"))
        val RANDOM_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/random.png"))
        val RELOAD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/reload.png"))
        val RESIZE_BOTH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-both.png"))
        val RESIZE_HEIGHT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-height.png"))
        val RESIZE_WIDTH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-width.png"))
        val RSS_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss.png"))
        val RSS_ALT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss-alt.png"))
        val SCRIPT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/script.png"))
        val SHARE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share.png"))
        val SHARE_BOXED_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share-boxed.png"))
        val SHIELD_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/shield.png"))
        val SIGNAL_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signal.png"))
        val SIGNPOST_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signpost.png"))
        val SORT_ASCENDING_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-ascending.png"))
        val SORT_DESCENDING_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-descending.png"))
        val SPREADSHEET_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/spreadsheet.png"))
        val STAR_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/star.png"))
        val SUN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sun.png"))
        val TABLET_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tablet.png"))
        val TAG_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tag.png"))
        val TAGS_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tags.png"))
        val TARGET_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/target.png"))
        val TASK_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/task.png"))
        val TERMINAL_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/terminal.png"))
        val TEXT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/text.png"))
        val THUMB_DOWN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-down.png"))
        val THUMB_UP_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-up.png"))
        val TIMER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/timer.png"))
        val TRANSFER_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/transfer.png"))
        val TRASH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/trash.png"))
        val UNDERLINE_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/underline.png"))
        val VERTICAL_ALIGN_BOTTOM_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-bottom.png"))
        val VERTICAL_ALIGN_CENTER_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-center.png"))
        val VERTICAL_ALIGN_TOP_8x8 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-top.png"))
        val VIDEO_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/video.png"))
        val VOLUME_HIGH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-high.png"))
        val VOLUME_LOW_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-low.png"))
        val VOLUME_OFF_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-off.png"))
        val WARNING_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/warning.png"))
        val WIFI_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wifi.png"))
        val WRENCH_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wrench.png"))
        val X_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/x.png"))
        val YEN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/yen.png"))
        val ZOOM_IN_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-in.png"))
        val ZOOM_OUT_8x8 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-out.png"))

        val ACCOUNT_LOGIN_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-login-2x.png"))
        val ACCOUNT_LOGOUT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-logout-2x.png"))
        val ACTION_REDO_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-redo-2x.png"))
        val ACTION_UNDO_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-undo-2x.png"))
        val ALIGN_CENTER_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-center-2x.png"))
        val ALIGN_LEFT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-left-2x.png"))
        val ALIGN_RIGHT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-right-2x.png"))
        val APERTURE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/aperture-2x.png"))
        val ARROW_BOTTOM_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-bottom-2x.png"))
        val ARROW_CIRCLE_BOTTOM_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-bottom-2x.png"))
        val ARROW_CIRCLE_LEFT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-left-2x.png"))
        val ARROW_CIRCLE_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-right-2x.png"))
        val ARROW_CIRCLE_TOP_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-top-2x.png"))
        val ARROW_LEFT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-left-2x.png"))
        val ARROW_RIGHT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-right-2x.png"))
        val ARROW_THICK_BOTTOM_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-bottom-2x.png"))
        val ARROW_THICK_LEFT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-left-2x.png"))
        val ARROW_THICK_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-right-2x.png"))
        val ARROW_THICK_TOP_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-top-2x.png"))
        val ARROW_TOP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-top-2x.png"))
        val AUDIO_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio-2x.png"))
        val AUDIO_SPECTRUM_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio-spectrum-2x.png"))
        val BADGE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/badge-2x.png"))
        val BAN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ban-2x.png"))
        val BAR_CHART_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bar-chart-2x.png"))
        val BASKET_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/basket-2x.png"))
        val BATTERY_EMPTY_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-empty-2x.png"))
        val BATTERY_FULL_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-full-2x.png"))
        val BEAKER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/beaker-2x.png"))
        val BELL_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bell-2x.png"))
        val BLUETOOTH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bluetooth-2x.png"))
        val BOLD_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bold-2x.png"))
        val BOLT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bolt-2x.png"))
        val BOOK_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/book-2x.png"))
        val BOOKMARK_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bookmark-2x.png"))
        val BOX_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/box-2x.png"))
        val BRIEFCASE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/briefcase-2x.png"))
        val BRITISH_POUND_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/british-pound-2x.png"))
        val BROWSER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/browser-2x.png"))
        val BRUSH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/brush-2x.png"))
        val BUG_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bug-2x.png"))
        val BULLHORN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bullhorn-2x.png"))
        val CALCULATOR_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calculator-2x.png"))
        val CALENDAR_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calendar-2x.png"))
        val CAMERA_SLR_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/camera-slr-2x.png"))
        val CARET_BOTTOM_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-bottom-2x.png"))
        val CARET_LEFT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-left-2x.png"))
        val CARET_RIGHT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-right-2x.png"))
        val CARET_TOP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-top-2x.png"))
        val CART_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cart-2x.png"))
        val CHAT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chat-2x.png"))
        val CHECK_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/check-2x.png"))
        val CHEVRON_BOTTOM_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-bottom-2x.png"))
        val CHEVRON_LEFT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-left-2x.png"))
        val CHEVRON_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-right-2x.png"))
        val CHEVRON_TOP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-top-2x.png"))
        val CIRCLE_CHECK_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-check-2x.png"))
        val CIRCLE_X_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-x-2x.png"))
        val CLIPBOARD_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clipboard-2x.png"))
        val CLOCK_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clock-2x.png"))
        val CLOUD_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-2x.png"))
        val CLOUD_DOWNLOAD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-download-2x.png"))
        val CLOUD_UPLOAD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-upload-2x.png"))
        val CLOUDY_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloudy-2x.png"))
        val CODE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/code-2x.png"))
        val COG_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cog-2x.png"))
        val COLLAPSE_DOWN_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-down-2x.png"))
        val COLLAPSE_LEFT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-left-2x.png"))
        val COLLAPSE_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-right-2x.png"))
        val COLLAPSE_UP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-up-2x.png"))
        val COMMAND_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/command-2x.png"))
        val COMMENT_SQUARE_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/comment-square-2x.png"))
        val COMPASS_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/compass-2x.png"))
        val CONTRAST_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/contrast-2x.png"))
        val COPYWRITING_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/copywriting-2x.png"))
        val CREDIT_CARD_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/credit-card-2x.png"))
        val CROP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/crop-2x.png"))
        val DASHBOARD_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dashboard-2x.png"))
        val DATA_TRANSFER_DOWNLOAD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-download-2x.png"))
        val DATA_TRANSFER_UPLOAD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-upload-2x.png"))
        val DELETE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/delete-2x.png"))
        val DIAL_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dial-2x.png"))
        val DOCUMENT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/document-2x.png"))
        val DOLLAR_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dollar-2x.png"))
        val DOUBLE_QUOTE_SANS_LEFT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-left-2x.png"))
        val DOUBLE_QUOTE_SANS_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-right-2x.png"))
        val DOUBLE_QUOTE_SERIF_LEFT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-left-2x.png"))
        val DOUBLE_QUOTE_SERIF_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-right-2x.png"))
        val DROPLET_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/droplet-2x.png"))
        val EJECT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eject-2x.png"))
        val ELEVATOR_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/elevator-2x.png"))
        val ELLIPSES_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ellipses-2x.png"))
        val ENVELOPE_CLOSED_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-closed-2x.png"))
        val ENVELOPE_OPEN_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-open-2x.png"))
        val EURO_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/euro-2x.png"))
        val EXCERPT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/excerpt-2x.png"))
        val EXPAND_DOWN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-down-2x.png"))
        val EXPAND_LEFT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-left-2x.png"))
        val EXPAND_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-right-2x.png"))
        val EXPAND_UP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-up-2x.png"))
        val EXTERNAL_LINK_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/external-link-2x.png"))
        val EYE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eye-2x.png"))
        val EYEDROPPER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eyedropper-2x.png"))
        val FILE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/file-2x.png"))
        val FIRE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fire-2x.png"))
        val FLAG_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flag-2x.png"))
        val FLASH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flash-2x.png"))
        val FOLDER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/folder-2x.png"))
        val FORK_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fork-2x.png"))
        val FULLSCREEN_ENTER_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-enter-2x.png"))
        val FULLSCREEN_EXIT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-exit-2x.png"))
        val GLOBE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/globe-2x.png"))
        val GRAPH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/graph-2x.png"))
        val GRID_FOUR_UP_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-four-up-2x.png"))
        val GRID_THREE_UP_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-three-up-2x.png"))
        val GRID_TWO_UP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-two-up-2x.png"))
        val HARD_DRIVE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/hard-drive-2x.png"))
        val HEADER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/header-2x.png"))
        val HEADPHONES_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/headphones-2x.png"))
        val HEART_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/heart-2x.png"))
        val HOME_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/home-2x.png"))
        val IMAGE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/image-2x.png"))
        val INBOX_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/inbox-2x.png"))
        val INFINITY_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/infinity-2x.png"))
        val INFO_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/info-2x.png"))
        val ITALIC_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/italic-2x.png"))
        val JUSTIFY_CENTER_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-center-2x.png"))
        val JUSTIFY_LEFT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-left-2x.png"))
        val JUSTIFY_RIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-right-2x.png"))
        val KEY_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/key-2x.png"))
        val LAPTOP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/laptop-2x.png"))
        val LAYERS_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/layers-2x.png"))
        val LIGHTBULB_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lightbulb-2x.png"))
        val LINK_BROKEN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-broken-2x.png"))
        val LINK_INTACT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-intact-2x.png"))
        val LIST_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list-2x.png"))
        val LIST_RICH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list-rich-2x.png"))
        val LOCATION_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/location-2x.png"))
        val LOCK_LOCKED_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-locked-2x.png"))
        val LOCK_UNLOCKED_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-unlocked-2x.png"))
        val LOOP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-2x.png"))
        val LOOP_CIRCULAR_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-circular-2x.png"))
        val LOOP_SQUARE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-square-2x.png"))
        val MAGNIFYING_GLASS_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/magnifying-glass-2x.png"))
        val MAP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map-2x.png"))
        val MAP_MARKER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map-marker-2x.png"))
        val MEDIA_PAUSE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-pause-2x.png"))
        val MEDIA_PLAY_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-play-2x.png"))
        val MEDIA_RECORD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-record-2x.png"))
        val MEDIA_SKIP_BACKWARD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-backward-2x.png"))
        val MEDIA_SKIP_FORWARD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-forward-2x.png"))
        val MEDIA_STEP_BACKWARD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-backward-2x.png"))
        val MEDIA_STEP_FORWARD_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-forward-2x.png"))
        val MEDIA_STOP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-stop-2x.png"))
        val MEDICAL_CROSS_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/medical-cross-2x.png"))
        val MENU_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/menu-2x.png"))
        val MICROPHONE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/microphone-2x.png"))
        val MINUS_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/minus-2x.png"))
        val MONITOR_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/monitor-2x.png"))
        val MOON_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/moon-2x.png"))
        val MOVE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/move-2x.png"))
        val MUSICAL_NOTE_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/musical-note-2x.png"))
        val PAPERCLIP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/paperclip-2x.png"))
        val PENCIL_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pencil-2x.png"))
        val PEOPLE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/people-2x.png"))
        val PERSON_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/person-2x.png"))
        val PHONE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/phone-2x.png"))
        val PIE_CHART_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pie-chart-2x.png"))
        val PIN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pin-2x.png"))
        val PLAY_CIRCLE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/play-circle-2x.png"))
        val PLUS_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/plus-2x.png"))
        val POWER_STANDBY_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/power-standby-2x.png"))
        val PRINT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/print-2x.png"))
        val PROJECT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/project-2x.png"))
        val PULSE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pulse-2x.png"))
        val PUZZLE_PIECE_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/puzzle-piece-2x.png"))
        val QUESTION_MARK_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/question-mark-2x.png"))
        val RAIN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rain-2x.png"))
        val RANDOM_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/random-2x.png"))
        val RELOAD_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/reload-2x.png"))
        val RESIZE_BOTH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-both-2x.png"))
        val RESIZE_HEIGHT_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-height-2x.png"))
        val RESIZE_WIDTH_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-width-2x.png"))
        val RSS_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss-2x.png"))
        val RSS_ALT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss-alt-2x.png"))
        val SCRIPT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/script-2x.png"))
        val SHARE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share-2x.png"))
        val SHARE_BOXED_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share-boxed-2x.png"))
        val SHIELD_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/shield-2x.png"))
        val SIGNAL_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signal-2x.png"))
        val SIGNPOST_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signpost-2x.png"))
        val SORT_ASCENDING_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-ascending-2x.png"))
        val SORT_DESCENDING_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-descending-2x.png"))
        val SPREADSHEET_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/spreadsheet-2x.png"))
        val STAR_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/star-2x.png"))
        val SUN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sun-2x.png"))
        val TABLET_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tablet-2x.png"))
        val TAG_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tag-2x.png"))
        val TAGS_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tags-2x.png"))
        val TARGET_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/target-2x.png"))
        val TASK_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/task-2x.png"))
        val TERMINAL_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/terminal-2x.png"))
        val TEXT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/text-2x.png"))
        val THUMB_DOWN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-down-2x.png"))
        val THUMB_UP_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-up-2x.png"))
        val TIMER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/timer-2x.png"))
        val TRANSFER_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/transfer-2x.png"))
        val TRASH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/trash-2x.png"))
        val UNDERLINE_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/underline-2x.png"))
        val VERTICAL_ALIGN_BOTTOM_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-bottom-2x.png"))
        val VERTICAL_ALIGN_CENTER_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-center-2x.png"))
        val VERTICAL_ALIGN_TOP_16x16 =
            ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-top-2x.png"))
        val VIDEO_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/video-2x.png"))
        val VOLUME_HIGH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-high-2x.png"))
        val VOLUME_LOW_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-low-2x.png"))
        val VOLUME_OFF_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-off-2x.png"))
        val WARNING_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/warning-2x.png"))
        val WIFI_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wifi-2x.png"))
        val WRENCH_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wrench-2x.png"))
        val X_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/x-2x.png"))
        val YEN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/yen-2x.png"))
        val ZOOM_IN_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-in-2x.png"))
        val ZOOM_OUT_16x16 = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-out-2x.png"))
    }

    object Advanced {
        val KOTLIN_8x8 = ImageIcon(this::class.java.getResource("/icons/kotlin_8x8.png"))
        val KOTLIN_16x16 = ImageIcon(this::class.java.getResource("/icons/kotlin_16x16.png"))
        val GROOVY_8x8 = ImageIcon(this::class.java.getResource("/icons/groovy_8x8.png"))
        val GROOVY_16x16 = ImageIcon(this::class.java.getResource("/icons/groovy_16x16.png"))
        val COPY_16x16 = ImageIcon(this::class.java.getResource("/icons/copy_16x16.png"))
    }
}
