package ru.ezhov.rocket.action.application.resources

import javax.swing.ImageIcon

object Icons {
    object Standard {
        object Small {
            val ACCOUNT_LOGIN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-login.png"))
            val ACCOUNT_LOGOUT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-logout.png"))
            val ACTION_REDO = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-redo.png"))
            val ACTION_UNDO = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-undo.png"))
            val ALIGN_CENTER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-center.png"))
            val ALIGN_LEFT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-left.png"))
            val ALIGN_RIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-right.png"))
            val APERTURE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/aperture.png"))
            val ARROW_BOTTOM = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-bottom.png"))
            val ARROW_CIRCLE_BOTTOM =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-bottom.png"))
            val ARROW_CIRCLE_LEFT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-left.png"))
            val ARROW_CIRCLE_RIGHT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-right.png"))
            val ARROW_CIRCLE_TOP =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-top.png"))
            val ARROW_LEFT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-left.png"))
            val ARROW_RIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-right.png"))
            val ARROW_THICK_BOTTOM =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-bottom.png"))
            val ARROW_THICK_LEFT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-left.png"))
            val ARROW_THICK_RIGHT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-right.png"))
            val ARROW_THICK_TOP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-top.png"))
            val ARROW_TOP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-top.png"))
            val AUDIO = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio.png"))
            val AUDIO_SPECTRUM = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio-spectrum.png"))
            val BADGE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/badge.png"))
            val BAN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ban.png"))
            val BAR_CHART = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bar-chart.png"))
            val BASKET = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/basket.png"))
            val BATTERY_EMPTY = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-empty.png"))
            val BATTERY_FULL = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-full.png"))
            val BEAKER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/beaker.png"))
            val BELL = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bell.png"))
            val BLUETOOTH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bluetooth.png"))
            val BOLD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bold.png"))
            val BOLT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bolt.png"))
            val BOOK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/book.png"))
            val BOOKMARK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bookmark.png"))
            val BOX = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/box.png"))
            val BRIEFCASE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/briefcase.png"))
            val BRITISH_POUND = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/british-pound.png"))
            val BROWSER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/browser.png"))
            val BRUSH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/brush.png"))
            val BUG = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bug.png"))
            val BULLHORN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bullhorn.png"))
            val CALCULATOR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calculator.png"))
            val CALENDAR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calendar.png"))
            val CAMERA_SLR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/camera-slr.png"))
            val CARET_BOTTOM = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-bottom.png"))
            val CARET_LEFT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-left.png"))
            val CARET_RIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-right.png"))
            val CARET_TOP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-top.png"))
            val CART = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cart.png"))
            val CHAT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chat.png"))
            val CHECK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/check.png"))
            val CHEVRON_BOTTOM = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-bottom.png"))
            val CHEVRON_LEFT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-left.png"))
            val CHEVRON_RIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-right.png"))
            val CHEVRON_TOP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-top.png"))
            val CIRCLE_CHECK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-check.png"))
            val CIRCLE_X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-x.png"))
            val CLIPBOARD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clipboard.png"))
            val CLOCK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clock.png"))
            val CLOUD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud.png"))
            val CLOUD_DOWNLOAD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-download.png"))
            val CLOUD_UPLOAD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-upload.png"))
            val CLOUDY = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloudy.png"))
            val CODE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/code.png"))
            val COG = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cog.png"))
            val COLLAPSE_DOWN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-down.png"))
            val COLLAPSE_LEFT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-left.png"))
            val COLLAPSE_RIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-right.png"))
            val COLLAPSE_UP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-up.png"))
            val COMMAND = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/command.png"))
            val COMMENT_SQUARE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/comment-square.png"))
            val COMPASS = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/compass.png"))
            val CONTRAST = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/contrast.png"))
            val COPYWRITING = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/copywriting.png"))
            val CREDIT_CARD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/credit-card.png"))
            val CROP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/crop.png"))
            val DASHBOARD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dashboard.png"))
            val DATA_TRANSFER_DOWNLOAD =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-download.png"))
            val DATA_TRANSFER_UPLOAD =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-upload.png"))
            val DELETE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/delete.png"))
            val DIAL = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dial.png"))
            val DOCUMENT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/document.png"))
            val DOLLAR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dollar.png"))
            val DOUBLE_QUOTE_SANS_LEFT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-left.png"))
            val DOUBLE_QUOTE_SANS_RIGHT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-right.png"))
            val DOUBLE_QUOTE_SERIF_LEFT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-left.png"))
            val DOUBLE_QUOTE_SERIF_RIGHT =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-right.png"))
            val DROPLET = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/droplet.png"))
            val EJECT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eject.png"))
            val ELEVATOR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/elevator.png"))
            val ELLIPSES = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ellipses.png"))
            val ENVELOPE_CLOSED = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-closed.png"))
            val ENVELOPE_OPEN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-open.png"))
            val EURO = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/euro.png"))
            val EXCERPT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/excerpt.png"))
            val EXPAND_DOWN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-down.png"))
            val EXPAND_LEFT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-left.png"))
            val EXPAND_RIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-right.png"))
            val EXPAND_UP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-up.png"))
            val EXTERNAL_LINK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/external-link.png"))
            val EYE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eye.png"))
            val EYEDROPPER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eyedropper.png"))
            val FILE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/file.png"))
            val FIRE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fire.png"))
            val FLAG = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flag.png"))
            val FLASH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flash.png"))
            val FOLDER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/folder.png"))
            val FORK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fork.png"))
            val FULLSCREEN_ENTER =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-enter.png"))
            val FULLSCREEN_EXIT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-exit.png"))
            val GLOBE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/globe.png"))
            val GRAPH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/graph.png"))
            val GRID_FOUR_UP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-four-up.png"))
            val GRID_THREE_UP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-three-up.png"))
            val GRID_TWO_UP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-two-up.png"))
            val HARD_DRIVE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/hard-drive.png"))
            val HEADER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/header.png"))
            val HEADPHONES = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/headphones.png"))
            val HEART = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/heart.png"))
            val HOME = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/home.png"))
            val IMAGE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/image.png"))
            val INBOX = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/inbox.png"))
            val INFINITY = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/infinity.png"))
            val INFO = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/info.png"))
            val ITALIC = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/italic.png"))
            val JUSTIFY_CENTER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-center.png"))
            val JUSTIFY_LEFT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-left.png"))
            val JUSTIFY_RIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-right.png"))
            val KEY = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/key.png"))
            val LAPTOP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/laptop.png"))
            val LAYERS = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/layers.png"))
            val LIGHTBULB = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lightbulb.png"))
            val LINK_BROKEN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-broken.png"))
            val LINK_INTACT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-intact.png"))
            val LIST = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list.png"))
            val LIST_RICH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list-rich.png"))
            val LOCATION = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/location.png"))
            val LOCK_LOCKED = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-locked.png"))
            val LOCK_UNLOCKED = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-unlocked.png"))
            val LOOP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop.png"))
            val LOOP_CIRCULAR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-circular.png"))
            val LOOP_SQUARE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-square.png"))
            val MAGNIFYING_GLASS =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/magnifying-glass.png"))
            val MAP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map.png"))
            val MAP_MARKER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map-marker.png"))
            val MEDIA_PAUSE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-pause.png"))
            val MEDIA_PLAY = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-play.png"))
            val MEDIA_RECORD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-record.png"))
            val MEDIA_SKIP_BACKWARD =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-backward.png"))
            val MEDIA_SKIP_FORWARD =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-forward.png"))
            val MEDIA_STEP_BACKWARD =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-backward.png"))
            val MEDIA_STEP_FORWARD =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-forward.png"))
            val MEDIA_STOP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-stop.png"))
            val MEDICAL_CROSS = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/medical-cross.png"))
            val MENU = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/menu.png"))
            val MICROPHONE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/microphone.png"))
            val MINUS = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/minus.png"))
            val MONITOR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/monitor.png"))
            val MOON = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/moon.png"))
            val MOVE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/move.png"))
            val MUSICAL_NOTE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/musical-note.png"))
            val PAPERCLIP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/paperclip.png"))
            val PENCIL = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pencil.png"))
            val PEOPLE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/people.png"))
            val PERSON = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/person.png"))
            val PHONE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/phone.png"))
            val PIE_CHART = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pie-chart.png"))
            val PIN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pin.png"))
            val PLAY_CIRCLE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/play-circle.png"))
            val PLUS = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/plus.png"))
            val POWER_STANDBY = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/power-standby.png"))
            val PRINT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/print.png"))
            val PROJECT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/project.png"))
            val PULSE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pulse.png"))
            val PUZZLE_PIECE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/puzzle-piece.png"))
            val QUESTION_MARK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/question-mark.png"))
            val RAIN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rain.png"))
            val RANDOM = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/random.png"))
            val RELOAD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/reload.png"))
            val RESIZE_BOTH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-both.png"))
            val RESIZE_HEIGHT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-height.png"))
            val RESIZE_WIDTH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-width.png"))
            val RSS = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss.png"))
            val RSS_ALT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss-alt.png"))
            val SCRIPT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/script.png"))
            val SHARE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share.png"))
            val SHARE_BOXED = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share-boxed.png"))
            val SHIELD = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/shield.png"))
            val SIGNAL = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signal.png"))
            val SIGNPOST = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signpost.png"))
            val SORT_ASCENDING = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-ascending.png"))
            val SORT_DESCENDING = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-descending.png"))
            val SPREADSHEET = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/spreadsheet.png"))
            val STAR = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/star.png"))
            val SUN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sun.png"))
            val TABLET = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tablet.png"))
            val TAG = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tag.png"))
            val TAGS = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tags.png"))
            val TARGET = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/target.png"))
            val TASK = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/task.png"))
            val TERMINAL = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/terminal.png"))
            val TEXT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/text.png"))
            val THUMB_DOWN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-down.png"))
            val THUMB_UP = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-up.png"))
            val TIMER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/timer.png"))
            val TRANSFER = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/transfer.png"))
            val TRASH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/trash.png"))
            val UNDERLINE = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/underline.png"))
            val VERTICAL_ALIGN_BOTTOM =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-bottom.png"))
            val VERTICAL_ALIGN_CENTER =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-center.png"))
            val VERTICAL_ALIGN_TOP =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-top.png"))
            val VIDEO = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/video.png"))
            val VOLUME_HIGH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-high.png"))
            val VOLUME_LOW = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-low.png"))
            val VOLUME_OFF = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-off.png"))
            val WARNING = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/warning.png"))
            val WIFI = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wifi.png"))
            val WRENCH = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wrench.png"))
            val X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/x.png"))
            val YEN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/yen.png"))
            val ZOOM_IN = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-in.png"))
            val ZOOM_OUT = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-out.png"))
        }


        object X2 {

            val ACCOUNT_LOGIN_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-login-2x.png"))
            val ACCOUNT_LOGOUT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/account-logout-2x.png"))
            val ACTION_REDO_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-redo-2x.png"))
            val ACTION_UNDO_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/action-undo-2x.png"))
            val ALIGN_CENTER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-center-2x.png"))
            val ALIGN_LEFT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-left-2x.png"))
            val ALIGN_RIGHT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/align-right-2x.png"))
            val APERTURE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/aperture-2x.png"))
            val ARROW_BOTTOM_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-bottom-2x.png"))
            val ARROW_CIRCLE_BOTTOM_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-bottom-2x.png"))
            val ARROW_CIRCLE_LEFT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-left-2x.png"))
            val ARROW_CIRCLE_RIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-right-2x.png"))
            val ARROW_CIRCLE_TOP_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-circle-top-2x.png"))
            val ARROW_LEFT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-left-2x.png"))
            val ARROW_RIGHT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-right-2x.png"))
            val ARROW_THICK_BOTTOM_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-bottom-2x.png"))
            val ARROW_THICK_LEFT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-left-2x.png"))
            val ARROW_THICK_RIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-right-2x.png"))
            val ARROW_THICK_TOP_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-thick-top-2x.png"))
            val ARROW_TOP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/arrow-top-2x.png"))
            val AUDIO_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio-2x.png"))
            val AUDIO_SPECTRUM_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/audio-spectrum-2x.png"))
            val BADGE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/badge-2x.png"))
            val BAN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ban-2x.png"))
            val BAR_CHART_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bar-chart-2x.png"))
            val BASKET_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/basket-2x.png"))
            val BATTERY_EMPTY_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-empty-2x.png"))
            val BATTERY_FULL_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/battery-full-2x.png"))
            val BEAKER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/beaker-2x.png"))
            val BELL_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bell-2x.png"))
            val BLUETOOTH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bluetooth-2x.png"))
            val BOLD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bold-2x.png"))
            val BOLT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bolt-2x.png"))
            val BOOK_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/book-2x.png"))
            val BOOKMARK_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bookmark-2x.png"))
            val BOX_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/box-2x.png"))
            val BRIEFCASE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/briefcase-2x.png"))
            val BRITISH_POUND_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/british-pound-2x.png"))
            val BROWSER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/browser-2x.png"))
            val BRUSH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/brush-2x.png"))
            val BUG_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bug-2x.png"))
            val BULLHORN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/bullhorn-2x.png"))
            val CALCULATOR_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calculator-2x.png"))
            val CALENDAR_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/calendar-2x.png"))
            val CAMERA_SLR_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/camera-slr-2x.png"))
            val CARET_BOTTOM_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-bottom-2x.png"))
            val CARET_LEFT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-left-2x.png"))
            val CARET_RIGHT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-right-2x.png"))
            val CARET_TOP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/caret-top-2x.png"))
            val CART_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cart-2x.png"))
            val CHAT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chat-2x.png"))
            val CHECK_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/check-2x.png"))
            val CHEVRON_BOTTOM_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-bottom-2x.png"))
            val CHEVRON_LEFT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-left-2x.png"))
            val CHEVRON_RIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-right-2x.png"))
            val CHEVRON_TOP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/chevron-top-2x.png"))
            val CIRCLE_CHECK_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-check-2x.png"))
            val CIRCLE_X_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/circle-x-2x.png"))
            val CLIPBOARD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clipboard-2x.png"))
            val CLOCK_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/clock-2x.png"))
            val CLOUD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-2x.png"))
            val CLOUD_DOWNLOAD_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-download-2x.png"))
            val CLOUD_UPLOAD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloud-upload-2x.png"))
            val CLOUDY_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cloudy-2x.png"))
            val CODE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/code-2x.png"))
            val COG_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/cog-2x.png"))
            val COLLAPSE_DOWN_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-down-2x.png"))
            val COLLAPSE_LEFT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-left-2x.png"))
            val COLLAPSE_RIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-right-2x.png"))
            val COLLAPSE_UP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/collapse-up-2x.png"))
            val COMMAND_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/command-2x.png"))
            val COMMENT_SQUARE_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/comment-square-2x.png"))
            val COMPASS_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/compass-2x.png"))
            val CONTRAST_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/contrast-2x.png"))
            val COPYWRITING_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/copywriting-2x.png"))
            val CREDIT_CARD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/credit-card-2x.png"))
            val CROP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/crop-2x.png"))
            val DASHBOARD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dashboard-2x.png"))
            val DATA_TRANSFER_DOWNLOAD_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-download-2x.png"))
            val DATA_TRANSFER_UPLOAD_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/data-transfer-upload-2x.png"))
            val DELETE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/delete-2x.png"))
            val DIAL_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dial-2x.png"))
            val DOCUMENT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/document-2x.png"))
            val DOLLAR_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/dollar-2x.png"))
            val DOUBLE_QUOTE_SANS_LEFT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-left-2x.png"))
            val DOUBLE_QUOTE_SANS_RIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-sans-right-2x.png"))
            val DOUBLE_QUOTE_SERIF_LEFT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-left-2x.png"))
            val DOUBLE_QUOTE_SERIF_RIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/double-quote-serif-right-2x.png"))
            val DROPLET_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/droplet-2x.png"))
            val EJECT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eject-2x.png"))
            val ELEVATOR_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/elevator-2x.png"))
            val ELLIPSES_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/ellipses-2x.png"))
            val ENVELOPE_CLOSED_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-closed-2x.png"))
            val ENVELOPE_OPEN_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/envelope-open-2x.png"))
            val EURO_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/euro-2x.png"))
            val EXCERPT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/excerpt-2x.png"))
            val EXPAND_DOWN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-down-2x.png"))
            val EXPAND_LEFT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-left-2x.png"))
            val EXPAND_RIGHT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-right-2x.png"))
            val EXPAND_UP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/expand-up-2x.png"))
            val EXTERNAL_LINK_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/external-link-2x.png"))
            val EYE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eye-2x.png"))
            val EYEDROPPER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/eyedropper-2x.png"))
            val FILE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/file-2x.png"))
            val FIRE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fire-2x.png"))
            val FLAG_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flag-2x.png"))
            val FLASH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/flash-2x.png"))
            val FOLDER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/folder-2x.png"))
            val FORK_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fork-2x.png"))
            val FULLSCREEN_ENTER_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-enter-2x.png"))
            val FULLSCREEN_EXIT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/fullscreen-exit-2x.png"))
            val GLOBE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/globe-2x.png"))
            val GRAPH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/graph-2x.png"))
            val GRID_FOUR_UP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-four-up-2x.png"))
            val GRID_THREE_UP_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-three-up-2x.png"))
            val GRID_TWO_UP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/grid-two-up-2x.png"))
            val HARD_DRIVE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/hard-drive-2x.png"))
            val HEADER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/header-2x.png"))
            val HEADPHONES_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/headphones-2x.png"))
            val HEART_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/heart-2x.png"))
            val HOME_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/home-2x.png"))
            val IMAGE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/image-2x.png"))
            val INBOX_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/inbox-2x.png"))
            val INFINITY_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/infinity-2x.png"))
            val INFO_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/info-2x.png"))
            val ITALIC_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/italic-2x.png"))
            val JUSTIFY_CENTER_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-center-2x.png"))
            val JUSTIFY_LEFT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-left-2x.png"))
            val JUSTIFY_RIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/justify-right-2x.png"))
            val KEY_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/key-2x.png"))
            val LAPTOP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/laptop-2x.png"))
            val LAYERS_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/layers-2x.png"))
            val LIGHTBULB_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lightbulb-2x.png"))
            val LINK_BROKEN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-broken-2x.png"))
            val LINK_INTACT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/link-intact-2x.png"))
            val LIST_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list-2x.png"))
            val LIST_RICH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/list-rich-2x.png"))
            val LOCATION_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/location-2x.png"))
            val LOCK_LOCKED_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-locked-2x.png"))
            val LOCK_UNLOCKED_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/lock-unlocked-2x.png"))
            val LOOP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-2x.png"))
            val LOOP_CIRCULAR_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-circular-2x.png"))
            val LOOP_SQUARE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/loop-square-2x.png"))
            val MAGNIFYING_GLASS_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/magnifying-glass-2x.png"))
            val MAP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map-2x.png"))
            val MAP_MARKER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/map-marker-2x.png"))
            val MEDIA_PAUSE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-pause-2x.png"))
            val MEDIA_PLAY_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-play-2x.png"))
            val MEDIA_RECORD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-record-2x.png"))
            val MEDIA_SKIP_BACKWARD_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-backward-2x.png"))
            val MEDIA_SKIP_FORWARD_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-skip-forward-2x.png"))
            val MEDIA_STEP_BACKWARD_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-backward-2x.png"))
            val MEDIA_STEP_FORWARD_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-step-forward-2x.png"))
            val MEDIA_STOP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/media-stop-2x.png"))
            val MEDICAL_CROSS_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/medical-cross-2x.png"))
            val MENU_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/menu-2x.png"))
            val MICROPHONE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/microphone-2x.png"))
            val MINUS_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/minus-2x.png"))
            val MONITOR_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/monitor-2x.png"))
            val MOON_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/moon-2x.png"))
            val MOVE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/move-2x.png"))
            val MUSICAL_NOTE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/musical-note-2x.png"))
            val PAPERCLIP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/paperclip-2x.png"))
            val PENCIL_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pencil-2x.png"))
            val PEOPLE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/people-2x.png"))
            val PERSON_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/person-2x.png"))
            val PHONE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/phone-2x.png"))
            val PIE_CHART_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pie-chart-2x.png"))
            val PIN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pin-2x.png"))
            val PLAY_CIRCLE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/play-circle-2x.png"))
            val PLUS_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/plus-2x.png"))
            val POWER_STANDBY_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/power-standby-2x.png"))
            val PRINT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/print-2x.png"))
            val PROJECT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/project-2x.png"))
            val PULSE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/pulse-2x.png"))
            val PUZZLE_PIECE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/puzzle-piece-2x.png"))
            val QUESTION_MARK_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/question-mark-2x.png"))
            val RAIN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rain-2x.png"))
            val RANDOM_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/random-2x.png"))
            val RELOAD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/reload-2x.png"))
            val RESIZE_BOTH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-both-2x.png"))
            val RESIZE_HEIGHT_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-height-2x.png"))
            val RESIZE_WIDTH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/resize-width-2x.png"))
            val RSS_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss-2x.png"))
            val RSS_ALT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/rss-alt-2x.png"))
            val SCRIPT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/script-2x.png"))
            val SHARE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share-2x.png"))
            val SHARE_BOXED_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/share-boxed-2x.png"))
            val SHIELD_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/shield-2x.png"))
            val SIGNAL_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signal-2x.png"))
            val SIGNPOST_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/signpost-2x.png"))
            val SORT_ASCENDING_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-ascending-2x.png"))
            val SORT_DESCENDING_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sort-descending-2x.png"))
            val SPREADSHEET_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/spreadsheet-2x.png"))
            val STAR_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/star-2x.png"))
            val SUN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/sun-2x.png"))
            val TABLET_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tablet-2x.png"))
            val TAG_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tag-2x.png"))
            val TAGS_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/tags-2x.png"))
            val TARGET_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/target-2x.png"))
            val TASK_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/task-2x.png"))
            val TERMINAL_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/terminal-2x.png"))
            val TEXT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/text-2x.png"))
            val THUMB_DOWN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-down-2x.png"))
            val THUMB_UP_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/thumb-up-2x.png"))
            val TIMER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/timer-2x.png"))
            val TRANSFER_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/transfer-2x.png"))
            val TRASH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/trash-2x.png"))
            val UNDERLINE_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/underline-2x.png"))
            val VERTICAL_ALIGN_BOTTOM_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-bottom-2x.png"))
            val VERTICAL_ALIGN_CENTER_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-center-2x.png"))
            val VERTICAL_ALIGN_TOP_2X =
                ImageIcon(this::class.java.getResource("/icons/open-iconic/png/vertical-align-top-2x.png"))
            val VIDEO_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/video-2x.png"))
            val VOLUME_HIGH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-high-2x.png"))
            val VOLUME_LOW_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-low-2x.png"))
            val VOLUME_OFF_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/volume-off-2x.png"))
            val WARNING_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/warning-2x.png"))
            val WIFI_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wifi-2x.png"))
            val WRENCH_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/wrench-2x.png"))
            val X_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/x-2x.png"))
            val YEN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/yen-2x.png"))
            val ZOOM_IN_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-in-2x.png"))
            val ZOOM_OUT_2X = ImageIcon(this::class.java.getResource("/icons/open-iconic/png/zoom-out-2x.png"))
        }
    }
}
