package ru.ezhov.rocket.action.plugin.noteonfile

import org.fife.ui.rsyntaxtextarea.SyntaxConstants

internal object StylesList {
    val styles = listOf(
        SyntaxConstants.SYNTAX_STYLE_NONE,
        SyntaxConstants.SYNTAX_STYLE_ACTIONSCRIPT,
        SyntaxConstants.SYNTAX_STYLE_ASSEMBLER_X86,
        SyntaxConstants.SYNTAX_STYLE_ASSEMBLER_6502,
        SyntaxConstants.SYNTAX_STYLE_BBCODE,
        SyntaxConstants.SYNTAX_STYLE_C,
        SyntaxConstants.SYNTAX_STYLE_CLOJURE,
        SyntaxConstants.SYNTAX_STYLE_CPLUSPLUS,
        SyntaxConstants.SYNTAX_STYLE_CSHARP,
        SyntaxConstants.SYNTAX_STYLE_CSS,
        SyntaxConstants.SYNTAX_STYLE_CSV,
        SyntaxConstants.SYNTAX_STYLE_D,
        SyntaxConstants.SYNTAX_STYLE_DOCKERFILE,
        SyntaxConstants.SYNTAX_STYLE_DART,
        SyntaxConstants.SYNTAX_STYLE_DELPHI,
        SyntaxConstants.SYNTAX_STYLE_DTD,
        SyntaxConstants.SYNTAX_STYLE_FORTRAN,
        SyntaxConstants.SYNTAX_STYLE_GO,
        SyntaxConstants.SYNTAX_STYLE_GROOVY,
        SyntaxConstants.SYNTAX_STYLE_HOSTS,
        SyntaxConstants.SYNTAX_STYLE_HTACCESS,
        SyntaxConstants.SYNTAX_STYLE_HTML,
        SyntaxConstants.SYNTAX_STYLE_INI,
        SyntaxConstants.SYNTAX_STYLE_JAVA,
        SyntaxConstants.SYNTAX_STYLE_JAVASCRIPT,
        SyntaxConstants.SYNTAX_STYLE_JSON,
        SyntaxConstants.SYNTAX_STYLE_JSON_WITH_COMMENTS,
        SyntaxConstants.SYNTAX_STYLE_JSP,
        SyntaxConstants.SYNTAX_STYLE_KOTLIN,
        SyntaxConstants.SYNTAX_STYLE_LATEX,
        SyntaxConstants.SYNTAX_STYLE_LESS,
        SyntaxConstants.SYNTAX_STYLE_LISP,
        SyntaxConstants.SYNTAX_STYLE_LUA,
        SyntaxConstants.SYNTAX_STYLE_MAKEFILE,
        SyntaxConstants.SYNTAX_STYLE_MARKDOWN,
        SyntaxConstants.SYNTAX_STYLE_MXML,
        SyntaxConstants.SYNTAX_STYLE_NSIS,
        SyntaxConstants.SYNTAX_STYLE_PERL,
        SyntaxConstants.SYNTAX_STYLE_PHP,
        SyntaxConstants.SYNTAX_STYLE_PROPERTIES_FILE,
        SyntaxConstants.SYNTAX_STYLE_PYTHON,
        SyntaxConstants.SYNTAX_STYLE_RUBY,
        SyntaxConstants.SYNTAX_STYLE_SAS,
        SyntaxConstants.SYNTAX_STYLE_SCALA,
        SyntaxConstants.SYNTAX_STYLE_SQL,
        SyntaxConstants.SYNTAX_STYLE_TCL,
        SyntaxConstants.SYNTAX_STYLE_TYPESCRIPT,
        SyntaxConstants.SYNTAX_STYLE_UNIX_SHELL,
        SyntaxConstants.SYNTAX_STYLE_VISUAL_BASIC,
        SyntaxConstants.SYNTAX_STYLE_WINDOWS_BATCH,
        SyntaxConstants.SYNTAX_STYLE_XML,
        SyntaxConstants.SYNTAX_STYLE_YAML,
    )
}